name: Deploy Doxygen Docs

on:
  push:
    branches:
      - main  # Replace with the branch where you generate the Doxygen documentation

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen

    - name: Generate Doxygen documentation
      run: doxygen

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html  # Replace with the directory containing your generated Doxygen HTML files
